-- WC 2026 active squads: Belgium + Iran (MD1 starters + unused squad members)
INSERT INTO players (id, name, country, position, game_id, previous_opponent, previous_points) VALUES
  ('bel-courtois', 'Courtois', 'Belgium', 'GK', 'bel-irn', 'Egypt', 0),
  ('bel-meunier', 'Meunier', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-ngoy', 'Ngoy', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-mechele', 'Mechele', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-castagne', 'Castagne', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-onana', 'Onana', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('bel-tielemans', 'Tielemans', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('bel-trossard', 'Trossard', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-debruyne', 'De Bruyne', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('bel-doku', 'Doku', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-lukaku', 'Lukaku', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-deketelaere', 'De Ketelaere', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-witsel', 'Witsel', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('irn-beiranvand', 'Beiranvand', 'Iran', 'GK', 'bel-irn', 'New Zealand', 0),
  ('irn-rezaeian', 'Rezaeian', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 10),
  ('irn-khalilzadeh', 'Khalilzadeh', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 0),
  ('irn-nemati', 'Nemati', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 0),
  ('irn-mohammadi', 'Mohammadi', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 0),
  ('irn-ghoddos', 'Ghoddos', 'Iran', 'MID', 'bel-irn', 'New Zealand', 0),
  ('irn-ezatolahi', 'Ezatolahi', 'Iran', 'MID', 'bel-irn', 'New Zealand', 0),
  ('irn-taremi', 'Taremi', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 0),
  ('irn-mohebi', 'Mohebi', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 10),
  ('irn-moghanlou', 'Moghanlou', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 0),
  ('irn-yousefi', 'Yousefi', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 0),
  ('irn-jahanbakhsh', 'Jahanbakhsh', 'Iran', 'MID', 'bel-irn', 'New Zealand', 0)
ON CONFLICT (id) DO NOTHING;
