-- WC 2026 active squads: Uruguay, Cabo Verde, New Zealand, Egypt (MD1 starters + unused squad members)
INSERT INTO players (id, name, country, position, game_id, previous_opponent, previous_points) VALUES
  ('uru-muslera', 'Muslera', 'Uruguay', 'GK', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-varela', 'Varela', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-caceres', 'Cáceres', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-olivera', 'Olivera', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-vina', 'Viña', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-valverde', 'Valverde', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-ugarte', 'Ugarte', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-bentancur', 'Bentancur', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-maraujo', 'M. Araújo', 'Uruguay', 'FWD', 'uru-cpv', 'Saudi Arabia', 10),
  ('uru-vinas', 'Viñas', 'Uruguay', 'FWD', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-nunez', 'Núñez', 'Uruguay', 'FWD', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-gimenez', 'Giménez', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-arrascaeta', 'De Arrascaeta', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-rajo', 'Ronald Araújo', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('cpv-vozinha', 'Vozinha', 'Cabo Verde', 'GK', 'uru-cpv', 'Spain', 8),
  ('cpv-moreira', 'Moreira', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-pico', 'Pico', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-diney', 'Diney', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-cabral', 'Cabral', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-pina', 'Pina', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('cpv-duarte', 'Duarte', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('cpv-monteiro', 'Monteiro', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('cpv-mendes', 'Mendes', 'Cabo Verde', 'FWD', 'uru-cpv', 'Spain', 0),
  ('cpv-livramento', 'Livramento', 'Cabo Verde', 'FWD', 'uru-cpv', 'Spain', 0),
  ('cpv-jovane', 'Jovane Cabral', 'Cabo Verde', 'FWD', 'uru-cpv', 'Spain', 0),
  ('cpv-rodrigues', 'Garry Rodrigues', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('nzl-crocombe', 'Crocombe', 'New Zealand', 'GK', 'nzl-egy', 'Iran', 0),
  ('nzl-payne', 'Payne', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-surman', 'Surman', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-boxall', 'Boxall', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-cacace', 'Cacace', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-singh', 'Singh', 'New Zealand', 'MID', 'nzl-egy', 'Iran', 0),
  ('nzl-bell', 'Bell', 'New Zealand', 'MID', 'nzl-egy', 'Iran', 0),
  ('nzl-stamenic', 'Stamenić', 'New Zealand', 'MID', 'nzl-egy', 'Iran', 0),
  ('nzl-just', 'Just', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 20),
  ('nzl-wood', 'Wood', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 0),
  ('nzl-mccowatt', 'McCowatt', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 0),
  ('nzl-rogerson', 'Rogerson', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 0),
  ('egy-shobeir', 'Shobeir', 'Egypt', 'GK', 'nzl-egy', 'Belgium', 0),
  ('egy-hany', 'Hany', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-ibrahim', 'Y. Ibrahim', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-fathy', 'Fathy', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-fatouh', 'Fatouh', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-attia', 'Attia', 'Egypt', 'MID', 'nzl-egy', 'Belgium', 0),
  ('egy-lasheen', 'Lasheen', 'Egypt', 'MID', 'nzl-egy', 'Belgium', 0),
  ('egy-ziko', 'Ziko', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0),
  ('egy-salah', 'Salah', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0),
  ('egy-ashour', 'Ashour', 'Egypt', 'MID', 'nzl-egy', 'Belgium', 10),
  ('egy-marmoush', 'Marmoush', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0),
  ('egy-trezeguet', 'Trézéguet', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0)
ON CONFLICT (id) DO NOTHING;
