-- Recalculate previous_points using captain scoring:
--   goals × 10 + assists × 5 + clean sheet × 8 (GK/DEF only)
-- Stats reflect WC 2026 group-stage Matchday 1 (15 Jun 2026).

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS previous_goals INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS previous_assists INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS previous_clean_sheet BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE players AS p
SET
  previous_opponent = v.opponent,
  previous_goals = v.goals,
  previous_assists = v.assists,
  previous_clean_sheet = v.clean_sheet,
  previous_points = v.goals * 10 + v.assists * 5 + CASE
    WHEN v.clean_sheet AND p.position IN ('GK', 'DEF') THEN 8
    ELSE 0
  END
FROM (
  VALUES
    ('esp-simon', 'Cabo Verde', 0, 0, TRUE),
    ('esp-llorente', 'Cabo Verde', 0, 0, TRUE),
    ('esp-cubarsi', 'Cabo Verde', 0, 0, TRUE),
    ('esp-laporte', 'Cabo Verde', 0, 0, TRUE),
    ('esp-cucurella', 'Cabo Verde', 0, 0, TRUE),
    ('esp-rodri', 'Cabo Verde', 0, 0, FALSE),
    ('esp-pedri', 'Cabo Verde', 0, 0, FALSE),
    ('esp-fabian', 'Cabo Verde', 0, 0, FALSE),
    ('esp-yamal', 'Cabo Verde', 0, 0, FALSE),
    ('esp-nwilliams', 'Cabo Verde', 0, 0, FALSE),
    ('esp-oyarzabal', 'Cabo Verde', 0, 0, FALSE),
    ('esp-gavi', 'Cabo Verde', 0, 0, FALSE),
    ('esp-ferran', 'Cabo Verde', 0, 0, FALSE),
    ('esp-olmo', 'Cabo Verde', 0, 0, FALSE),
    ('esp-merino', 'Cabo Verde', 0, 0, FALSE),
    ('sau-owais', 'Uruguay', 0, 0, FALSE),
    ('sau-abdulhamid', 'Uruguay', 0, 0, FALSE),
    ('sau-tambakti', 'Uruguay', 0, 0, FALSE),
    ('sau-amri', 'Uruguay', 1, 0, FALSE),
    ('sau-harbi', 'Uruguay', 0, 0, FALSE),
    ('sau-shamat', 'Uruguay', 0, 0, FALSE),
    ('sau-kanno', 'Uruguay', 0, 0, FALSE),
    ('sau-khaibari', 'Uruguay', 0, 0, FALSE),
    ('sau-salem', 'Uruguay', 0, 0, FALSE),
    ('sau-buraikan', 'Uruguay', 0, 0, FALSE),
    ('sau-juwayr', 'Uruguay', 0, 0, FALSE),
    ('sau-shehri', 'Uruguay', 0, 0, FALSE),
    ('bel-courtois', 'Egypt', 0, 0, FALSE),
    ('bel-meunier', 'Egypt', 0, 0, FALSE),
    ('bel-ngoy', 'Egypt', 0, 0, FALSE),
    ('bel-mechele', 'Egypt', 0, 0, FALSE),
    ('bel-castagne', 'Egypt', 0, 0, FALSE),
    ('bel-onana', 'Egypt', 0, 0, FALSE),
    ('bel-tielemans', 'Egypt', 0, 0, FALSE),
    ('bel-trossard', 'Egypt', 0, 0, FALSE),
    ('bel-debruyne', 'Egypt', 0, 0, FALSE),
    ('bel-doku', 'Egypt', 0, 0, FALSE),
    ('bel-lukaku', 'Egypt', 0, 0, FALSE),
    ('bel-deketelaere', 'Egypt', 0, 0, FALSE),
    ('bel-witsel', 'Egypt', 0, 0, FALSE),
    ('irn-beiranvand', 'New Zealand', 0, 0, FALSE),
    ('irn-rezaeian', 'New Zealand', 1, 0, FALSE),
    ('irn-khalilzadeh', 'New Zealand', 0, 0, FALSE),
    ('irn-nemati', 'New Zealand', 0, 0, FALSE),
    ('irn-mohammadi', 'New Zealand', 0, 0, FALSE),
    ('irn-ghoddos', 'New Zealand', 0, 0, FALSE),
    ('irn-ezatolahi', 'New Zealand', 0, 0, FALSE),
    ('irn-taremi', 'New Zealand', 0, 0, FALSE),
    ('irn-mohebi', 'New Zealand', 1, 0, FALSE),
    ('irn-moghanlou', 'New Zealand', 0, 0, FALSE),
    ('irn-yousefi', 'New Zealand', 0, 0, FALSE),
    ('irn-jahanbakhsh', 'New Zealand', 0, 0, FALSE),
    ('uru-muslera', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-varela', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-caceres', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-olivera', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-vina', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-valverde', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-ugarte', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-bentancur', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-maraujo', 'Saudi Arabia', 1, 0, FALSE),
    ('uru-vinas', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-nunez', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-gimenez', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-arrascaeta', 'Saudi Arabia', 0, 0, FALSE),
    ('uru-rajo', 'Saudi Arabia', 0, 0, FALSE),
    ('cpv-vozinha', 'Spain', 0, 0, TRUE),
    ('cpv-moreira', 'Spain', 0, 0, TRUE),
    ('cpv-pico', 'Spain', 0, 0, TRUE),
    ('cpv-diney', 'Spain', 0, 0, TRUE),
    ('cpv-cabral', 'Spain', 0, 0, TRUE),
    ('cpv-pina', 'Spain', 0, 0, FALSE),
    ('cpv-duarte', 'Spain', 0, 0, FALSE),
    ('cpv-monteiro', 'Spain', 0, 0, FALSE),
    ('cpv-mendes', 'Spain', 0, 0, FALSE),
    ('cpv-livramento', 'Spain', 0, 0, FALSE),
    ('cpv-jovane', 'Spain', 0, 0, FALSE),
    ('cpv-rodrigues', 'Spain', 0, 0, FALSE),
    ('nzl-crocombe', 'Iran', 0, 0, FALSE),
    ('nzl-payne', 'Iran', 0, 0, FALSE),
    ('nzl-surman', 'Iran', 0, 0, FALSE),
    ('nzl-boxall', 'Iran', 0, 0, FALSE),
    ('nzl-cacace', 'Iran', 0, 0, FALSE),
    ('nzl-singh', 'Iran', 0, 0, FALSE),
    ('nzl-bell', 'Iran', 0, 0, FALSE),
    ('nzl-stamenic', 'Iran', 0, 0, FALSE),
    ('nzl-just', 'Iran', 2, 0, FALSE),
    ('nzl-wood', 'Iran', 0, 0, FALSE),
    ('nzl-mccowatt', 'Iran', 0, 0, FALSE),
    ('nzl-rogerson', 'Iran', 0, 0, FALSE),
    ('egy-shobeir', 'Belgium', 0, 0, FALSE),
    ('egy-hany', 'Belgium', 0, 0, FALSE),
    ('egy-ibrahim', 'Belgium', 0, 0, FALSE),
    ('egy-fathy', 'Belgium', 0, 0, FALSE),
    ('egy-fatouh', 'Belgium', 0, 0, FALSE),
    ('egy-attia', 'Belgium', 0, 0, FALSE),
    ('egy-lasheen', 'Belgium', 0, 0, FALSE),
    ('egy-ziko', 'Belgium', 0, 0, FALSE),
    ('egy-salah', 'Belgium', 0, 0, FALSE),
    ('egy-ashour', 'Belgium', 1, 0, FALSE),
    ('egy-marmoush', 'Belgium', 0, 0, FALSE),
    ('egy-trezeguet', 'Belgium', 0, 0, FALSE)
) AS v(id, opponent, goals, assists, clean_sheet)
WHERE p.id = v.id;
