-- Replace captain pool with WC 2026 active squads (MD1 starters + unused squad members).
-- Clears captain picks that reference removed fantasy/legacy names.

DELETE FROM captain_selections
WHERE player_id NOT IN (
  -- Spain
  'esp-simon', 'esp-llorente', 'esp-cubarsi', 'esp-laporte', 'esp-cucurella',
  'esp-rodri', 'esp-pedri', 'esp-fabian', 'esp-yamal', 'esp-nwilliams', 'esp-oyarzabal',
  'esp-gavi', 'esp-ferran', 'esp-olmo', 'esp-merino',
  -- Saudi Arabia
  'sau-owais', 'sau-abdulhamid', 'sau-tambakti', 'sau-amri', 'sau-harbi',
  'sau-shamat', 'sau-kanno', 'sau-khaibari', 'sau-salem', 'sau-buraikan', 'sau-juwayr', 'sau-shehri',
  -- Belgium
  'bel-courtois', 'bel-meunier', 'bel-ngoy', 'bel-mechele', 'bel-castagne',
  'bel-onana', 'bel-tielemans', 'bel-trossard', 'bel-debruyne', 'bel-doku', 'bel-lukaku',
  'bel-deketelaere', 'bel-witsel',
  -- Iran
  'irn-beiranvand', 'irn-rezaeian', 'irn-khalilzadeh', 'irn-nemati', 'irn-mohammadi',
  'irn-ghoddos', 'irn-ezatolahi', 'irn-taremi', 'irn-mohebi', 'irn-moghanlou', 'irn-yousefi', 'irn-jahanbakhsh',
  -- Uruguay
  'uru-muslera', 'uru-varela', 'uru-caceres', 'uru-olivera', 'uru-vina',
  'uru-valverde', 'uru-ugarte', 'uru-bentancur', 'uru-maraujo', 'uru-vinas', 'uru-nunez',
  'uru-gimenez', 'uru-arrascaeta', 'uru-rajo',
  -- Cabo Verde
  'cpv-vozinha', 'cpv-moreira', 'cpv-pico', 'cpv-diney', 'cpv-cabral',
  'cpv-pina', 'cpv-duarte', 'cpv-monteiro', 'cpv-mendes', 'cpv-livramento', 'cpv-jovane', 'cpv-rodrigues',
  -- New Zealand
  'nzl-crocombe', 'nzl-payne', 'nzl-surman', 'nzl-boxall', 'nzl-cacace',
  'nzl-singh', 'nzl-bell', 'nzl-stamenic', 'nzl-just', 'nzl-wood', 'nzl-mccowatt', 'nzl-rogerson',
  -- Egypt
  'egy-shobeir', 'egy-hany', 'egy-ibrahim', 'egy-fathy', 'egy-fatouh',
  'egy-attia', 'egy-lasheen', 'egy-ziko', 'egy-salah', 'egy-ashour', 'egy-marmoush', 'egy-trezeguet'
);

DELETE FROM players
WHERE id NOT IN (
  'esp-simon', 'esp-llorente', 'esp-cubarsi', 'esp-laporte', 'esp-cucurella',
  'esp-rodri', 'esp-pedri', 'esp-fabian', 'esp-yamal', 'esp-nwilliams', 'esp-oyarzabal',
  'esp-gavi', 'esp-ferran', 'esp-olmo', 'esp-merino',
  'sau-owais', 'sau-abdulhamid', 'sau-tambakti', 'sau-amri', 'sau-harbi',
  'sau-shamat', 'sau-kanno', 'sau-khaibari', 'sau-salem', 'sau-buraikan', 'sau-juwayr', 'sau-shehri',
  'bel-courtois', 'bel-meunier', 'bel-ngoy', 'bel-mechele', 'bel-castagne',
  'bel-onana', 'bel-tielemans', 'bel-trossard', 'bel-debruyne', 'bel-doku', 'bel-lukaku',
  'bel-deketelaere', 'bel-witsel',
  'irn-beiranvand', 'irn-rezaeian', 'irn-khalilzadeh', 'irn-nemati', 'irn-mohammadi',
  'irn-ghoddos', 'irn-ezatolahi', 'irn-taremi', 'irn-mohebi', 'irn-moghanlou', 'irn-yousefi', 'irn-jahanbakhsh',
  'uru-muslera', 'uru-varela', 'uru-caceres', 'uru-olivera', 'uru-vina',
  'uru-valverde', 'uru-ugarte', 'uru-bentancur', 'uru-maraujo', 'uru-vinas', 'uru-nunez',
  'uru-gimenez', 'uru-arrascaeta', 'uru-rajo',
  'cpv-vozinha', 'cpv-moreira', 'cpv-pico', 'cpv-diney', 'cpv-cabral',
  'cpv-pina', 'cpv-duarte', 'cpv-monteiro', 'cpv-mendes', 'cpv-livramento', 'cpv-jovane', 'cpv-rodrigues',
  'nzl-crocombe', 'nzl-payne', 'nzl-surman', 'nzl-boxall', 'nzl-cacace',
  'nzl-singh', 'nzl-bell', 'nzl-stamenic', 'nzl-just', 'nzl-wood', 'nzl-mccowatt', 'nzl-rogerson',
  'egy-shobeir', 'egy-hany', 'egy-ibrahim', 'egy-fathy', 'egy-fatouh',
  'egy-attia', 'egy-lasheen', 'egy-ziko', 'egy-salah', 'egy-ashour', 'egy-marmoush', 'egy-trezeguet'
);

INSERT INTO players (id, name, country, position, game_id, previous_opponent, previous_points) VALUES
  ('esp-simon', 'Simón', 'Spain', 'GK', 'esp-sau', 'Cabo Verde', 8),
  ('esp-llorente', 'Llorente', 'Spain', 'DEF', 'esp-sau', 'Cabo Verde', 8),
  ('esp-cubarsi', 'Cubarsí', 'Spain', 'DEF', 'esp-sau', 'Cabo Verde', 8),
  ('esp-laporte', 'Laporte', 'Spain', 'DEF', 'esp-sau', 'Cabo Verde', 8),
  ('esp-cucurella', 'Cucurella', 'Spain', 'DEF', 'esp-sau', 'Cabo Verde', 8),
  ('esp-rodri', 'Rodri', 'Spain', 'MID', 'esp-sau', 'Cabo Verde', 0),
  ('esp-pedri', 'Pedri', 'Spain', 'MID', 'esp-sau', 'Cabo Verde', 0),
  ('esp-fabian', 'Fabián Ruiz', 'Spain', 'MID', 'esp-sau', 'Cabo Verde', 0),
  ('esp-yamal', 'Yamal', 'Spain', 'FWD', 'esp-sau', 'Cabo Verde', 0),
  ('esp-nwilliams', 'N. Williams', 'Spain', 'FWD', 'esp-sau', 'Cabo Verde', 0),
  ('esp-oyarzabal', 'Oyarzabal', 'Spain', 'FWD', 'esp-sau', 'Cabo Verde', 0),
  ('esp-gavi', 'Gavi', 'Spain', 'MID', 'esp-sau', 'Cabo Verde', 0),
  ('esp-ferran', 'Ferran Torres', 'Spain', 'FWD', 'esp-sau', 'Cabo Verde', 0),
  ('esp-olmo', 'Dani Olmo', 'Spain', 'FWD', 'esp-sau', 'Cabo Verde', 0),
  ('esp-merino', 'Merino', 'Spain', 'MID', 'esp-sau', 'Cabo Verde', 0),
  ('sau-owais', 'Al-Owais', 'Saudi Arabia', 'GK', 'esp-sau', 'Uruguay', 0),
  ('sau-abdulhamid', 'Abdulhamid', 'Saudi Arabia', 'DEF', 'esp-sau', 'Uruguay', 0),
  ('sau-tambakti', 'Al-Tambakti', 'Saudi Arabia', 'DEF', 'esp-sau', 'Uruguay', 0),
  ('sau-amri', 'Al-Amri', 'Saudi Arabia', 'DEF', 'esp-sau', 'Uruguay', 10),
  ('sau-harbi', 'Al-Harbi', 'Saudi Arabia', 'DEF', 'esp-sau', 'Uruguay', 0),
  ('sau-shamat', 'Abu Al-Shamat', 'Saudi Arabia', 'MID', 'esp-sau', 'Uruguay', 0),
  ('sau-kanno', 'Kanno', 'Saudi Arabia', 'MID', 'esp-sau', 'Uruguay', 0),
  ('sau-khaibari', 'Al-Khaibari', 'Saudi Arabia', 'MID', 'esp-sau', 'Uruguay', 0),
  ('sau-salem', 'Al-Dawsari', 'Saudi Arabia', 'MID', 'esp-sau', 'Uruguay', 0),
  ('sau-buraikan', 'Al-Buraikan', 'Saudi Arabia', 'FWD', 'esp-sau', 'Uruguay', 0),
  ('sau-juwayr', 'Al-Juwayr', 'Saudi Arabia', 'FWD', 'esp-sau', 'Uruguay', 0),
  ('sau-shehri', 'Al-Shehri', 'Saudi Arabia', 'FWD', 'esp-sau', 'Uruguay', 0),
  ('bel-courtois', 'Courtois', 'Belgium', 'GK', 'bel-irn', 'Egypt', 0),
  ('bel-meunier', 'Meunier', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-ngoy', 'Ngoy', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-mechele', 'Mechele', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-castagne', 'Castagne', 'Belgium', 'DEF', 'bel-irn', 'Egypt', 0),
  ('bel-onana', 'Onana', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('bel-tielemans', 'Tielemans', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('bel-trossard', 'Trossard', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-debruyne', 'De Bruyne', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('bel-doku', 'Doku', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-lukaku', 'Lukaku', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-deketelaere', 'De Ketelaere', 'Belgium', 'FWD', 'bel-irn', 'Egypt', 0),
  ('bel-witsel', 'Witsel', 'Belgium', 'MID', 'bel-irn', 'Egypt', 0),
  ('irn-beiranvand', 'Beiranvand', 'Iran', 'GK', 'bel-irn', 'New Zealand', 0),
  ('irn-rezaeian', 'Rezaeian', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 10),
  ('irn-khalilzadeh', 'Khalilzadeh', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 0),
  ('irn-nemati', 'Nemati', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 0),
  ('irn-mohammadi', 'Mohammadi', 'Iran', 'DEF', 'bel-irn', 'New Zealand', 0),
  ('irn-ghoddos', 'Ghoddos', 'Iran', 'MID', 'bel-irn', 'New Zealand', 0),
  ('irn-ezatolahi', 'Ezatolahi', 'Iran', 'MID', 'bel-irn', 'New Zealand', 0),
  ('irn-taremi', 'Taremi', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 0),
  ('irn-mohebi', 'Mohebi', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 10),
  ('irn-moghanlou', 'Moghanlou', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 0),
  ('irn-yousefi', 'Yousefi', 'Iran', 'FWD', 'bel-irn', 'New Zealand', 0),
  ('irn-jahanbakhsh', 'Jahanbakhsh', 'Iran', 'MID', 'bel-irn', 'New Zealand', 0),
  ('uru-muslera', 'Muslera', 'Uruguay', 'GK', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-varela', 'Varela', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-caceres', 'Cáceres', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-olivera', 'Olivera', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-vina', 'Viña', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-valverde', 'Valverde', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-ugarte', 'Ugarte', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-bentancur', 'Bentancur', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-maraujo', 'M. Araújo', 'Uruguay', 'FWD', 'uru-cpv', 'Saudi Arabia', 10),
  ('uru-vinas', 'Viñas', 'Uruguay', 'FWD', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-nunez', 'Núñez', 'Uruguay', 'FWD', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-gimenez', 'Giménez', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-arrascaeta', 'De Arrascaeta', 'Uruguay', 'MID', 'uru-cpv', 'Saudi Arabia', 0),
  ('uru-rajo', 'Ronald Araújo', 'Uruguay', 'DEF', 'uru-cpv', 'Saudi Arabia', 0),
  ('cpv-vozinha', 'Vozinha', 'Cabo Verde', 'GK', 'uru-cpv', 'Spain', 8),
  ('cpv-moreira', 'Moreira', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-pico', 'Pico', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-diney', 'Diney', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-cabral', 'Cabral', 'Cabo Verde', 'DEF', 'uru-cpv', 'Spain', 8),
  ('cpv-pina', 'Pina', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('cpv-duarte', 'Duarte', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('cpv-monteiro', 'Monteiro', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('cpv-mendes', 'Mendes', 'Cabo Verde', 'FWD', 'uru-cpv', 'Spain', 0),
  ('cpv-livramento', 'Livramento', 'Cabo Verde', 'FWD', 'uru-cpv', 'Spain', 0),
  ('cpv-jovane', 'Jovane Cabral', 'Cabo Verde', 'FWD', 'uru-cpv', 'Spain', 0),
  ('cpv-rodrigues', 'Garry Rodrigues', 'Cabo Verde', 'MID', 'uru-cpv', 'Spain', 0),
  ('nzl-crocombe', 'Crocombe', 'New Zealand', 'GK', 'nzl-egy', 'Iran', 0),
  ('nzl-payne', 'Payne', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-surman', 'Surman', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-boxall', 'Boxall', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-cacace', 'Cacace', 'New Zealand', 'DEF', 'nzl-egy', 'Iran', 0),
  ('nzl-singh', 'Singh', 'New Zealand', 'MID', 'nzl-egy', 'Iran', 0),
  ('nzl-bell', 'Bell', 'New Zealand', 'MID', 'nzl-egy', 'Iran', 0),
  ('nzl-stamenic', 'Stamenić', 'New Zealand', 'MID', 'nzl-egy', 'Iran', 0),
  ('nzl-just', 'Just', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 20),
  ('nzl-wood', 'Wood', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 0),
  ('nzl-mccowatt', 'McCowatt', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 0),
  ('nzl-rogerson', 'Rogerson', 'New Zealand', 'FWD', 'nzl-egy', 'Iran', 0),
  ('egy-shobeir', 'Shobeir', 'Egypt', 'GK', 'nzl-egy', 'Belgium', 0),
  ('egy-hany', 'Hany', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-ibrahim', 'Y. Ibrahim', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-fathy', 'Fathy', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-fatouh', 'Fatouh', 'Egypt', 'DEF', 'nzl-egy', 'Belgium', 0),
  ('egy-attia', 'Attia', 'Egypt', 'MID', 'nzl-egy', 'Belgium', 0),
  ('egy-lasheen', 'Lasheen', 'Egypt', 'MID', 'nzl-egy', 'Belgium', 0),
  ('egy-ziko', 'Ziko', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0),
  ('egy-salah', 'Salah', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0),
  ('egy-ashour', 'Ashour', 'Egypt', 'MID', 'nzl-egy', 'Belgium', 10),
  ('egy-marmoush', 'Marmoush', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0),
  ('egy-trezeguet', 'Trézéguet', 'Egypt', 'FWD', 'nzl-egy', 'Belgium', 0)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  position = EXCLUDED.position,
  game_id = EXCLUDED.game_id,
  previous_opponent = EXCLUDED.previous_opponent,
  previous_points = EXCLUDED.previous_points,
  goals = 0,
  assists = 0,
  clean_sheet = FALSE;

UPDATE players
SET previous_goals = 0, previous_assists = 0, previous_clean_sheet = FALSE
WHERE game_id IN ('esp-sau', 'bel-irn', 'uru-cpv', 'nzl-egy');

UPDATE players AS p
SET
  previous_goals = v.goals,
  previous_assists = v.assists,
  previous_clean_sheet = v.clean_sheet,
  previous_points = v.goals * 10 + v.assists * 5 + CASE
    WHEN v.clean_sheet AND p.position IN ('GK', 'DEF') THEN 8
    ELSE 0
  END
FROM (
  VALUES
    ('esp-simon', 0, 0, TRUE),
    ('esp-llorente', 0, 0, TRUE),
    ('esp-cubarsi', 0, 0, TRUE),
    ('esp-laporte', 0, 0, TRUE),
    ('esp-cucurella', 0, 0, TRUE),
    ('esp-rodri', 0, 0, FALSE),
    ('esp-pedri', 0, 0, FALSE),
    ('esp-fabian', 0, 0, FALSE),
    ('esp-yamal', 0, 0, FALSE),
    ('esp-nwilliams', 0, 0, FALSE),
    ('esp-oyarzabal', 0, 0, FALSE),
    ('esp-gavi', 0, 0, FALSE),
    ('esp-ferran', 0, 0, FALSE),
    ('esp-olmo', 0, 0, FALSE),
    ('esp-merino', 0, 0, FALSE),
    ('sau-owais', 0, 0, FALSE),
    ('sau-abdulhamid', 0, 0, FALSE),
    ('sau-tambakti', 0, 0, FALSE),
    ('sau-amri', 1, 0, FALSE),
    ('sau-harbi', 0, 0, FALSE),
    ('sau-shamat', 0, 0, FALSE),
    ('sau-kanno', 0, 0, FALSE),
    ('sau-khaibari', 0, 0, FALSE),
    ('sau-salem', 0, 0, FALSE),
    ('sau-buraikan', 0, 0, FALSE),
    ('sau-juwayr', 0, 0, FALSE),
    ('sau-shehri', 0, 0, FALSE),
    ('bel-courtois', 0, 0, FALSE),
    ('bel-meunier', 0, 0, FALSE),
    ('bel-ngoy', 0, 0, FALSE),
    ('bel-mechele', 0, 0, FALSE),
    ('bel-castagne', 0, 0, FALSE),
    ('bel-onana', 0, 0, FALSE),
    ('bel-tielemans', 0, 0, FALSE),
    ('bel-trossard', 0, 0, FALSE),
    ('bel-debruyne', 0, 0, FALSE),
    ('bel-doku', 0, 0, FALSE),
    ('bel-lukaku', 0, 0, FALSE),
    ('bel-deketelaere', 0, 0, FALSE),
    ('bel-witsel', 0, 0, FALSE),
    ('irn-beiranvand', 0, 0, FALSE),
    ('irn-rezaeian', 1, 0, FALSE),
    ('irn-khalilzadeh', 0, 0, FALSE),
    ('irn-nemati', 0, 0, FALSE),
    ('irn-mohammadi', 0, 0, FALSE),
    ('irn-ghoddos', 0, 0, FALSE),
    ('irn-ezatolahi', 0, 0, FALSE),
    ('irn-taremi', 0, 0, FALSE),
    ('irn-mohebi', 1, 0, FALSE),
    ('irn-moghanlou', 0, 0, FALSE),
    ('irn-yousefi', 0, 0, FALSE),
    ('irn-jahanbakhsh', 0, 0, FALSE),
    ('uru-muslera', 0, 0, FALSE),
    ('uru-varela', 0, 0, FALSE),
    ('uru-caceres', 0, 0, FALSE),
    ('uru-olivera', 0, 0, FALSE),
    ('uru-vina', 0, 0, FALSE),
    ('uru-valverde', 0, 0, FALSE),
    ('uru-ugarte', 0, 0, FALSE),
    ('uru-bentancur', 0, 0, FALSE),
    ('uru-maraujo', 1, 0, FALSE),
    ('uru-vinas', 0, 0, FALSE),
    ('uru-nunez', 0, 0, FALSE),
    ('uru-gimenez', 0, 0, FALSE),
    ('uru-arrascaeta', 0, 0, FALSE),
    ('uru-rajo', 0, 0, FALSE),
    ('cpv-vozinha', 0, 0, TRUE),
    ('cpv-moreira', 0, 0, TRUE),
    ('cpv-pico', 0, 0, TRUE),
    ('cpv-diney', 0, 0, TRUE),
    ('cpv-cabral', 0, 0, TRUE),
    ('cpv-pina', 0, 0, FALSE),
    ('cpv-duarte', 0, 0, FALSE),
    ('cpv-monteiro', 0, 0, FALSE),
    ('cpv-mendes', 0, 0, FALSE),
    ('cpv-livramento', 0, 0, FALSE),
    ('cpv-jovane', 0, 0, FALSE),
    ('cpv-rodrigues', 0, 0, FALSE),
    ('nzl-crocombe', 0, 0, FALSE),
    ('nzl-payne', 0, 0, FALSE),
    ('nzl-surman', 0, 0, FALSE),
    ('nzl-boxall', 0, 0, FALSE),
    ('nzl-cacace', 0, 0, FALSE),
    ('nzl-singh', 0, 0, FALSE),
    ('nzl-bell', 0, 0, FALSE),
    ('nzl-stamenic', 0, 0, FALSE),
    ('nzl-just', 2, 0, FALSE),
    ('nzl-wood', 0, 0, FALSE),
    ('nzl-mccowatt', 0, 0, FALSE),
    ('nzl-rogerson', 0, 0, FALSE),
    ('egy-shobeir', 0, 0, FALSE),
    ('egy-hany', 0, 0, FALSE),
    ('egy-ibrahim', 0, 0, FALSE),
    ('egy-fathy', 0, 0, FALSE),
    ('egy-fatouh', 0, 0, FALSE),
    ('egy-attia', 0, 0, FALSE),
    ('egy-lasheen', 0, 0, FALSE),
    ('egy-ziko', 0, 0, FALSE),
    ('egy-salah', 0, 0, FALSE),
    ('egy-ashour', 1, 0, FALSE),
    ('egy-marmoush', 0, 0, FALSE),
    ('egy-trezeguet', 0, 0, FALSE)
) AS v(id, goals, assists, clean_sheet)
WHERE p.id = v.id;
